### PR TITLE
[DRAFT; DO NOT MERGE] Completion icons UI

### PR DESCRIPTION
**Pull request by ryantberg**
Light:
Screen Shot 2020-03-24 at 2 47 30 PM

Dark:
Screen Shot 2020-03-24 at 2 47 46 PM

Icon used is black, but should be white ideally. Leaving the coloring choice up to the completion providers

### CODE REVIEW

**Comment by edzkite** [comment]
Was it not possible to render the icon with the type, like in Atom?

kite

If not, @its-dhung what do you think of potentially having the Kite logo supplant the type here?

**Comment by metalogical** [comment]
@edzkite can the completer extension not achieve the overlay by generating an appropriate SVG, based on the type hint?

I think this implementation is enough -- would hesitate to do something too fancy in core if an extension can implement it just as well.

**Comment by metalogical** [comment]
@ryantberg Is it possible for an extension detect the color scheme, and generate an appropriate SVG based off that? If so, that validates the choice to give leave the icon entirely to the extension, without trying to "adapt" it to the color scheme.

**Comment by ryantberg** [comment]
I was thinking that our approach was what @metalogical said above--that the completion provider renders the type in their icon if they think that information is relevant.

As for the color scheme, the current type-colors are scheme-irrelevant hardcoded colors, so unless I'm missing something it seems like there doesn't need to be any adapting.

**Comment by edzkite** [comment]
> I was thinking that our approach was what @metalogical said above--that the completion provider renders the type in their icon if they think that information is relevant.

While that makes sense in principle, given that we'd be an extension author as well, how would we create an icon that contains both the type and the Kite logo,  since all we can send to the API is an image? I'd imagine to achieve that, you'd either need to create SVG assets for each type, or programmatically create a SVG that superimposes the Kite logo on top of the first letter of the type. Is there another way that we could do so without that much overhead?

> As for the color scheme, the current type-colors are scheme-irrelevant hardcoded colors, so unless I'm missing something it seems like there doesn't need to be any adapting.

Just to make sure we're all on the same page, the color-scheme here refers to the background color of the type node, i.e. blue for functions, brown for params. This is hard coded, internal to JupyterLab, and doesn't change based on the theme.

Since we're introducing icons now, is the concern if the logo should adjust accordingly based on the theme of the IDE?

**Comment by metalogical** [comment]
> While that makes sense in principle, given that we'd be an extension author as well, how would we create an icon that contains both the type and the Kite logo, since all we can send to the API is an image? I'd imagine to achieve that, you'd either need to create SVG assets for each type, or programmatically create a SVG that superimposes the Kite logo on top of the first letter of the type. Is there another way that we could do so without that much overhead?

Generating an SVG is pretty straightforward with JS: it's just an XML file, so can be manipulated with standard JS DOM functionality. It supports directly embedding text via the `<text>` tag, and we can embed the Kite icon SVG quite easily.

> Since we're introducing icons now, is the concern if the logo should adjust accordingly based on the theme of the IDE?

Yes that was the concern, but it seems like this shouldn't be a big deal based on Ryan's response.

**Review by edzkite — COMMENTED** [review]
I'm fine with having the extension be responsible for the icon, whether it's rendering the type or making sure it looks good agnostic of the theme, and implementation wise, I don't see any other issues.

I think the next steps here is to check in with @its-dhung and the Quansight UX team.

**Review by metalogical — APPROVED** [review]

**Pull request closed without merging**
